version: '3'

services:
  domino:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'francisconazevedo/php-service:7.4'
    container_name: domino_app
    restart: always
    volumes:
      - ".:/app"
    working_dir: "/app"
    ports:
      - '82:80'
    networks:
      - app-network

  myapp-mysql:
    image: 'mysql:8.0'
    container_name: myapp-mysql
    working_dir: /var/www/myapp
    volumes:
      - .dbdata:/var/bin/mysql
    ports:
      - "8107:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
