version: '3'

services:
  domino:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'francisconazevedo/php-service:7.4'
    container_name: domino_app
    restart: always
    volumes:
      - ".:/app"
    working_dir: "/app"
    ports:
      - '82:80'
    networks:
      - app-network
  mysql:
    image: mysql:5.7.22
    ports:
      - "3306:3306"
    volumes:
      - .dbdata:/var/bin/mysql
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
